name: GitHub Action For Running Tosca
run-name: ${{ github.actor }} is Running Tosca Tests via the AOS API 🚀
on: [push]
jobs:
  Execute-Tosca-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check if the TestEvents.json file exists in the repo
        shell: pwsh
        run: Test-Path TestEvents.json | Should -Be $true
